# Generated by Django 3.1.7 on 2021-03-08 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosproduit',
            options={'ordering': ('qtyInStock',)},
        ),
        migrations.RemoveField(
            model_name='infosproduit',
            name='tigID',
        ),
    ]
