# Generated by Django 3.1.7 on 2021-03-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0003_auto_20210309_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infosproduit',
            options={'ordering': ('tigID', 'quantityInStock')},
        ),
        migrations.RenameField(
            model_name='infosproduit',
            old_name='qtyInStock',
            new_name='quantityInStock',
        ),
    ]
