# Generated by Django 3.1.7 on 2021-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0004_auto_20210315_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='infosproduit',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='infosproduit',
            name='category',
            field=models.IntegerField(default='-1'),
        ),
        migrations.AddField(
            model_name='infosproduit',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='infosproduit',
            name='discount',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='infosproduit',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='infosproduit',
            name='owner',
            field=models.CharField(blank=True, default='tig', max_length=20),
        ),
        migrations.AddField(
            model_name='infosproduit',
            name='price',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='infosproduit',
            name='sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infosproduit',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
