# Generated by Django 3.1.7 on 2021-03-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0006_infosproduit_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tigID', models.IntegerField(default='-1')),
                ('price', models.FloatField(default='0')),
                ('quantity', models.IntegerField(default='0')),
                ('type', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
